const PROGRAM = {
  'Upper A': [['L-Sit Practice',4,'10–20 sec','60–90 sec'],['Pull-up',4,'5–8','2–3 min'],['Parallel Bar Dip',4,'6–10','2–3 min'],['One-arm DB Row',3,'8–12 / side','90 sec'],['Pike Push-up',3,'6–12','90–120 sec'],['DB Lateral Raise',4,'12–20','45–75 sec'],['DB Curl',3,'10–15','60 sec'],['Hanging Knee Raise',3,'10–15','60 sec']],
  'Lower + Core': [['DB Squat',3,'6–10','2 min'],['DB Romanian Deadlift',3,'8–12','2 min'],['Reverse Lunge',2,'8–10 / side','90 sec'],['Single-leg Calf Raise',3,'12–20 / side','60 sec'],['Tibialis Raise',2,'15–25','45–60 sec'],['Hanging Leg Raise',3,'8–15','60 sec'],['Side Plank',2,'30–60 sec / side','45 sec']],
  'Upper B': [['Handstand Practice',1,'5–10 min','as needed'],['Chin-up',4,'6–10','2 min'],['Pseudo Planche Push-up',3,'6–12','90–120 sec'],['DB Floor Press',3,'8–12','90 sec'],['DB Shoulder Press',3,'8–12','90 sec'],['DB Lateral Raise',4,'15–25','45–60 sec'],['DB Curl',3,'10–15','60 sec']],
  'Recovery': [['Mobility / Recovery',1,'15–25 min','—']],
  'Quality Run': [['Quality Run',1,'See plan','—']], 'Easy Run': [['Easy Run',1,'30–60 min','—']], 'Long Run': [['Long Run',1,'Easy distance','—']]
};
const DAYS = [['Mon','Upper A'],['Tue','Lower + Core'],['Wed','Recovery'],['Thu','Upper B'],['Fri','Quality Run'],['Sat','Easy Run'],['Sun','Long Run']];
const QUALITY = ['Easy 30–40 min (re-entry)','Tempo: 10–15 min WU + 20 min tempo + 10 min CD','Intervals: 5×3 min hard-controlled / 2 min jog','Easy 30 min — DELOAD','Tempo: 25 min continuous','Intervals: 6×3 min / 2 min jog','Easy 35–45 min','Easy 30 min — DELOAD','Tempo: 30 min','Intervals: 5×4 min / 2 min jog','Easy 35–45 min','Easy 30 min — DELOAD'];
const LONG = [8,10,12,8,14,16,18,12,20,22,24,16];
const store = { get:()=>JSON.parse(localStorage.getItem('hybrid-train-data')||'{}'), set:d=>localStorage.setItem('hybrid-train-data',JSON.stringify(d)) };
let data = store.get(); data.start ||= '2026-08-24'; data.logs ||= []; data.sessions ||= {}; data.custom ||= []; data.body ||= []; data.tab = 'home'; store.set(data);
let tick, timer = {seconds:0,running:false,mode:'session'};
let exerciseTick, exerciseTimer = {seconds:0,running:false,mode:'set',exercise:-1,rest:90};
let toastTick, audioContext, soundLoop;
function toast(message){let old=$('#toast');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div id="toast" class="toast">${esc(message)}</div>`);clearTimeout(toastTick);toastTick=setTimeout(()=>$('#toast')?.remove(),3200)}
function armSuccessChime(){try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();audioContext.resume()}catch{}}
function playSuccessChime(){try{armSuccessChime();[523.25,659.25,783.99,1046.5].forEach((freq,index)=>{let osc=audioContext.createOscillator(),gain=audioContext.createGain(),at=audioContext.currentTime+index*.13;osc.type='triangle';osc.frequency.setValueAtTime(freq,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(.2,at+.018);gain.gain.exponentialRampToValueAtTime(.0001,at+.34);osc.connect(gain).connect(audioContext.destination);osc.start(at);osc.stop(at+.36)})}catch{}}
function completeRest(){renderExerciseModal();clearInterval(soundLoop);playSuccessChime();soundLoop=setInterval(playSuccessChime,1300);document.body.insertAdjacentHTML('beforeend',`<div class="rest-complete" id="restComplete"><div class="rest-complete-card"><span class="label">rest complete</span><div class="complete-mark">✓</div><h2>พักครบแล้ว!</h2><p>พร้อมสำหรับเซ็ตถัดไป</p><button class="primary" onclick="dismissRestComplete()">ไปต่อ / ปิดเสียง</button></div></div>`)}
window.dismissRestComplete=()=>{clearInterval(soundLoop);$('#restComplete')?.remove()};
const $ = s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today = ()=>new Date().toISOString().slice(0,10);
function weekOf(date=today()){ const n=Math.floor((new Date(date+'T12:00')-new Date(data.start+'T12:00'))/6048e5)+1; return Math.max(1,n) }
function fmt(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function dateFor(w,i){let d=new Date(data.start+'T12:00');d.setDate(d.getDate()+(w-1)*7+i);return d.toISOString().slice(0,10)}
function save(){store.set(data)}
function nav(){return `<nav class="nav">${[['home','⌂','วันนี้'],['plan','▤','โปรแกรม'],['log','✚','บันทึก'],['more','•••','เพิ่มเติม']].map(x=>`<button class="${data.tab===x[0]?'active':''}" onclick="go('${x[0]}')"><i>${x[1]}</i>${x[2]}</button>`).join('')}</nav>`}
function header(){return `<header class="top"><div><div class="brand">HYBRID <span>//</span> TRAIN</div><div class="sub">Aesthetic calisthenics + marathon</div></div><div class="week">WEEK ${weekOf()}</div></header>`}
function planned(date=today()){let d=new Date(date+'T12:00'), day=(d.getDay()+6)%7, w=weekOf(date);let [name,session]=DAYS[day];let target=session==='Long Run'?`${LONG[Math.min(w,12)-1]||8} km easy`:session==='Quality Run'?QUALITY[Math.min(w,12)-1]||QUALITY[0]:session==='Easy Run'?'30–60 min easy, RPE 2–4':session==='Recovery'?'15–25 min mobility':session==='Upper A'?'RIR 1–3':session==='Lower + Core'?'RIR 2–3': 'Aesthetic + skill';return {date,name,session,target,w}}
function home(){const p=planned();let dates=DAYS.map((_,i)=>dateFor(p.w,i));let completed=Object.entries(data.sessions).filter(([k,x])=>x.done&&dates.some(d=>k.startsWith(d+'-'))).length;let km=data.logs.filter(x=>x.type==='run').reduce((s,x)=>s+Number(x.distance||0),0);return `${header()}<section class="card hero"><div class="label">วันนี้ · ${p.name}</div><h1>${p.session}</h1><p class="detail">${p.target}</p><button class="primary" onclick="startPlanned()">เริ่มเซสชัน</button></section><div class="grid"><div class="metric"><span class="label">สัปดาห์นี้</span><b>${completed}</b><span class="small">เซสชันเสร็จ</span></div><div class="metric"><span class="label">วิ่งสะสม</span><b>${km.toFixed(1)}</b><span class="small">กม.</span></div><div class="metric"><span class="label">บันทึก</span><b>${data.logs.length}</b><span class="small">รายการ</span></div></div><h2 class="section-title">สัปดาห์นี้</h2><section class="card">${DAYS.map(([day,session],i)=>{let d=dateFor(p.w,i),s=data.sessions[`${d}-${session}`];return `<div class="item"><div class="row"><div><h3>${day} · ${session}</h3><p>${d} · ${session==='Long Run'?`${LONG[Math.min(p.w,12)-1]||8} km easy`:session==='Quality Run'?QUALITY[Math.min(p.w,12)-1]:''}</p></div><span class="pill ${s?.done?'done':''}">${s?.done?'เสร็จแล้ว':'รอทำ'}</span></div></div>`}).join('')}</section>${nav()}`}
function plan(){let w=weekOf();return `${header()}<div class="row"><h2 class="section-title" style="margin-top:0">โปรแกรมสัปดาห์ ${w}</h2><button class="secondary" onclick="openCustom()">+ ออกแบบเอง</button></div><p class="hint">ดึงมาจากไฟล์ Hybrid Aesthetic Calisthenics + Marathon ของคุณ แก้ไขโปรแกรมเองได้จากปุ่มด้านบน</p><section class="card">${DAYS.map(([day,session],i)=>{let d=dateFor(w,i),ex=PROGRAM[session]||[];return `<div class="item"><div class="row"><div><span class="label">${day} · ${d}</span><h3>${session}</h3><p>${session==='Long Run'?`${LONG[Math.min(w,12)-1]||8} km easy`:session==='Quality Run'?QUALITY[Math.min(w,12)-1]:ex.map(x=>x[0]).join(' · ')}</p></div><button class="secondary" onclick="openSession('${session}','${d}')">เปิด</button></div></div>`}).join('')}</section><h2 class="section-title">โปรแกรมที่ออกแบบเอง</h2><section class="card">${data.custom.length?data.custom.map((c,i)=>`<div class="item"><div class="row"><div><h3>${esc(c.name)}</h3><p>${c.items.length} ท่า · ${c.items.map(x=>esc(x.name)).join(', ')}</p></div><button class="secondary" onclick="openCustomSession(${i})">เริ่ม</button></div></div>`).join(''):'<div class="empty">ยังไม่มีโปรแกรมส่วนตัว<br><span class="small">กด “ออกแบบเอง” เพื่อเริ่มสร้าง</span></div>'}</section>${nav()}`}
function sessionView(session,date,items){ let key=date+'-'+session, st=data.sessions[key]||{sets:{}}; let total=items.reduce((n,x)=>n+x[1],0),done=items.reduce((n,x,i)=>n+(st.sets?.[i]||[]).filter(v=>v.done).length,0); return `${header()}<div class="row"><div><span class="label">${date}</span><h2 class="section-title" style="margin:2px 0">${esc(session)}</h2></div><button class="secondary" onclick="go('plan')">← กลับ</button></div><section class="card game-head"><div class="row"><div><div class="label">mission progress</div><b>${done} / ${total} เซ็ต</b></div><div class="xp">${Math.round(done/total*100)||0}%</div></div><div class="progress"><i style="width:${done/total*100}%"></i></div><div class="row gap"><span class="small">เวลารวม <b id="time">${fmt(timer.seconds)}</b></span><button class="secondary" onclick="toggleTimer()">${timer.running?'หยุดเวลา':'เริ่มเวลา'}</button></div></section><section class="exercise-menu">${items.map((x,i)=>exerciseButton(x,i,st)).join('')}</section><button class="primary full" onclick="finishSession('${esc(key)}')">จบเซสชันของวันนี้ ✓</button>${nav()}`}
function exerciseButton(x,i,st){let [name,n,reps,rest]=x,done=(st.sets?.[i]||[]).filter(v=>v.done).length;return `<button class="exercise-card ${done===n?'cleared':''}" onclick="openExercise(${i})"><span class="exercise-number">${String(i+1).padStart(2,'0')}</span><span class="exercise-info"><b>${esc(name)}</b><small>${n} × ${esc(reps)} · พัก ${esc(rest)}</small></span><span class="exercise-status">${done===n?'✓':`${done}/${n}`}<em>${done===n?'CLEAR':'PLAY'}</em></span></button>`}
function logView(){return `${header()}<div class="row"><h2 class="section-title" style="margin-top:0">บันทึกผล</h2><button class="secondary" onclick="openRun()">+ บันทึกวิ่ง</button></div><section class="card"><div class="label">ประวัติล่าสุด</div>${data.logs.length?data.logs.slice().reverse().slice(0,20).map(x=>`<div class="item"><div class="row"><div><h3>${x.type==='run'?'🏃 '+esc(x.session):'💪 '+esc(x.session)}</h3><p>${x.date} · ${x.type==='run'?`${x.distance} km · ${x.duration} min · RPE ${x.rpe||'—'}`:x.summary}</p></div><button class="icon" onclick="deleteLog('${x.id}')">×</button></div></div>`).join(''):'<div class="empty">ยังไม่มีบันทึก<br><span class="small">ทำเซสชันหรือกด “บันทึกวิ่ง”</span></div>'}</section>${nav()}`}
function more(){return `${header()}<h2 class="section-title" style="margin-top:0">ข้อมูลและการตั้งค่า</h2><section class="card"><div class="label">เริ่มโปรแกรม</div><div class="form"><label>วันเริ่ม<input type="date" value="${data.start}" onchange="data.start=this.value;save();render()"></label><label>สัปดาห์ปัจจุบัน<input value="${weekOf()}" disabled></label></div></section><section class="card"><div class="label">สำรองข้อมูล</div><p class="hint">ข้อมูลเก็บใน iPhone/เบราว์เซอร์เครื่องนี้โดยอัตโนมัติ ใช้ Export เก็บไฟล์สำรองก่อนเปลี่ยนเครื่อง</p><button class="secondary" onclick="exportData()">Export ข้อมูล</button> <button class="secondary" onclick="$('#importFile').click()">Import ข้อมูล</button><input id="importFile" hidden type="file" accept="application/json" onchange="importData(this.files[0])"></section><section class="card"><div class="label">ติดตั้งบน iPhone</div><p class="hint">เปิดเว็บนี้ใน Safari → Share → Add to Home Screen เพื่อใช้งานเต็มจอเหมือนแอป</p></section>${nav()}`}
function render(){let content=data.tab==='home'?home():data.tab==='plan'?plan():data.tab==='log'?logView():more();$('#app').innerHTML=content}
window.go=t=>{data.tab=t;save();render()}; window.openSession=(s,d)=>{let it=PROGRAM[s]||[];data.tab='session';data.active={s,d,it};save();renderSession()}; window.openCustomSession=i=>{let c=data.custom[i];data.tab='session';data.active={s:c.name,d:today(),it:c.items.map(x=>[x.name,x.sets,x.reps,x.rest])};save();renderSession()}; window.startPlanned=()=>{let p=planned();openSession(p.session,p.date)};
function renderSession(){let a=data.active;if(!a){go('home');return} $('#app').innerHTML=sessionView(a.s,a.d,a.it)}
window.toggleTimer=()=>{timer.running=!timer.running;if(timer.running){clearInterval(tick);tick=setInterval(()=>{timer.seconds++;let el=$('#time');if(el)el.textContent=fmt(timer.seconds)},1000)}else clearInterval(tick);renderSession()}; window.resetTimer=()=>{timer.seconds=0;timer.running=false;clearInterval(tick);renderSession()};
window.openExercise=i=>{clearInterval(exerciseTick); exerciseTimer={seconds:0,running:false,mode:'set',exercise:i,rest:90}; renderExerciseModal()};
function renderExerciseModal(){let a=data.active, i=exerciseTimer.exercise, x=a.it[i], [name,n,reps,rest]=x, key=a.d+'-'+a.s, st=data.sessions[key]||{sets:{}};let vals=st.sets?.[i]||[], j=0; while(j<n&&vals[j]?.done)j++; if(j===n)j=n-1; let current=vals[j]||{}; let restChoices=[45,60,90,120,180],chosen=exerciseTimer.rest||90; closeModal(); modal(`<div class="game-modal"><div class="row"><div><span class="label">exercise ${String(i+1).padStart(2,'0')} · set ${j+1}/${n}</span><h2>${esc(name)}</h2></div><button class="icon" aria-label="ปิด" onclick="closeExercise()">×</button></div><p class="target">TARGET: ${esc(reps)} <span>•</span> REST: ${esc(rest)}</p><div class="set-clock"><div class="label">${exerciseTimer.mode==='rest'?'พักฟื้น':'จับเวลาเซ็ต'}</div><div class="time" id="exerciseTime">${fmt(exerciseTimer.seconds)}</div><div id="timerState" class="small">${exerciseTimer.mode==='rest'?'หายใจให้พร้อม แล้วไปต่อ':'กดเริ่มเมื่อเริ่มทำเซ็ต'}</div></div><div class="timer-actions"><button class="primary" onclick="toggleExerciseTimer()">${exerciseTimer.running?(exerciseTimer.mode==='rest'?'หยุดพัก':'หยุดเวลา'):(exerciseTimer.mode==='rest'?'เริ่มพัก':'เริ่มเซ็ต')}</button><button class="secondary" onclick="resetExerciseTimer()">รีเซ็ต</button></div><div class="form set-form"><label>จำนวนครั้ง<input id="modalReps" ${exerciseTimer.mode==='rest'?'disabled':''} type="number" min="0" step="1" inputmode="numeric" placeholder="เช่น 10" value="${esc(current.reps||'')}"></label><label>น้ำหนัก (kg)<input id="modalLoad" ${exerciseTimer.mode==='rest'?'disabled':''} type="number" min="0" step="0.25" inputmode="decimal" placeholder="เช่น 15" value="${esc(current.load||'')}"></label><label class="full-span">พักหลังจบเซ็ต<input id="modalRest" type="hidden" value="${chosen}"><span class="rest-picker">${restChoices.map(s=>`<button type="button" ${exerciseTimer.mode==='rest'?'disabled':''} class="${s===chosen?'selected':''}" data-rest="${s}" onclick="pickRest(${s})">${s}s</button>`).join('')}</span><button type="button" class="sound-test" onclick="armSuccessChime();playSuccessChime()">🔊 ทดสอบเสียง</button></label></div>${exerciseTimer.mode==='rest'?`<button class="primary full" onclick="skipRest()">ไปเซ็ต ${Math.min(j+1,n)} →</button>`:`<button class="primary full finish-set" onclick="finishExerciseSet(${i},${j})">จบเซ็ต ${j+1} + เริ่มพัก</button>`}<div class="set-dots">${Array.from({length:n},(_,k)=>`<i class="${vals[k]?.done?'done':k===j?'active':''}">${k+1}</i>`).join('')}</div></div>`,false)}
window.pickRest=s=>{exerciseTimer.rest=s;$('#modalRest').value=s;document.querySelectorAll('[data-rest]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.rest)===s))}; window.toggleExerciseTimer=()=>{exerciseTimer.running=!exerciseTimer.running;clearInterval(exerciseTick);if(exerciseTimer.running)exerciseTick=setInterval(()=>{if(exerciseTimer.mode==='rest'){exerciseTimer.seconds--;if(exerciseTimer.seconds<=0){exerciseTimer.seconds=0;exerciseTimer.running=false;clearInterval(exerciseTick);completeRest()}}else exerciseTimer.seconds++;let el=$('#exerciseTime');if(el)el.textContent=fmt(exerciseTimer.seconds)},1000);renderExerciseModal()};window.resetExerciseTimer=()=>{exerciseTimer.seconds=0;exerciseTimer.running=false;clearInterval(exerciseTick);renderExerciseModal()};
window.finishExerciseSet=(i,j)=>{let reps=$('#modalReps').value.trim(),load=$('#modalLoad').value.trim(),rest=Number($('#modalRest').value);if(!reps){alert('กรอกจำนวนครั้งให้ครบก่อน');return}armSuccessChime();let a=data.active,key=a.d+'-'+a.s,st=data.sessions[key]||{sets:{}};st.sets[i] ||= [];st.sets[i][j]={reps,load,done:true,duration:exerciseTimer.seconds};data.sessions[key]=st;save();exerciseTimer={seconds:rest,running:true,mode:'rest',exercise:i,rest};clearInterval(exerciseTick);exerciseTick=setInterval(()=>{exerciseTimer.seconds--;let el=$('#exerciseTime');if(el)el.textContent=fmt(Math.max(exerciseTimer.seconds,0));if(exerciseTimer.seconds<=0){exerciseTimer.seconds=0;exerciseTimer.running=false;clearInterval(exerciseTick);completeRest()}},1000);renderExerciseModal()};window.skipRest=()=>{clearInterval(exerciseTick);exerciseTimer={seconds:0,running:false,mode:'set',exercise:exerciseTimer.exercise,rest:90};renderExerciseModal()};window.closeExercise=()=>{clearInterval(exerciseTick);closeModal();renderSession()};
window.setVal=(i,j,k,v)=>{let a=data.active,key=a.d+'-'+a.s,st=data.sessions[key]||{sets:{}};st.sets[i] ||= []; st.sets[i][j] ||= {};st.sets[i][j][k]=v;data.sessions[key]=st;save()}; window.finishSession=key=>{let a=data.active,st=data.sessions[key]||{sets:{}};st.done=true;data.sessions[key]=st;let rows=a.it.map((x,i)=>`${x[0]}: ${(st.sets[i]||[]).filter(z=>z.done).map(z=>`${z.reps||'?'} (${fmt(z.duration||0)})`).join('/')||'—'}`).join(' · ');data.logs.push({id:crypto.randomUUID(),type:'strength',date:a.d,session:a.s,summary:rows});save();timer={seconds:0,running:false,mode:'session'};go('log')};
window.openRun=()=>modal(`<h2>บันทึกการวิ่ง</h2><div class="form"><label>วันที่<input id="rdate" type="date" value="${today()}"></label><label>ประเภท<select id="rtype"><option>Easy Run</option><option>Quality Run</option><option>Long Run</option><option>Custom Run</option></select></label><label>ระยะทาง (km)<input id="rdist" type="number" step="0.01" placeholder="5.0"></label><label>เวลา (นาที)<input id="rdur" type="number" step="0.1" placeholder="30"></label><label>RPE (1–10)<input id="rrpe" type="number" min="1" max="10"></label><label class="full-span">โน้ต<textarea id="rnote" placeholder="เส้นทาง, รองเท้า, ความรู้สึก..."></textarea></label></div><button class="primary full" onclick="saveRun()">บันทึกการวิ่ง</button>`); window.saveRun=()=>{let d={id:crypto.randomUUID(),type:'run',date:$('#rdate').value,session:$('#rtype').value,distance:$('#rdist').value,duration:$('#rdur').value,rpe:$('#rrpe').value,note:$('#rnote').value};if(!d.distance||!d.duration){toast('กรอกระยะทางและเวลาให้ครบ');return}data.logs.push(d);save();closeModal();go('log')};
window.openCustom=()=>modal(`<h2>ออกแบบโปรแกรม</h2><p class="hint">เพิ่มท่าทีละบรรทัด รูปแบบ: ชื่อท่า | จำนวนเซ็ต | reps/เวลา | เวลาพัก</p><div class="form"><label class="full-span">ชื่อโปรแกรม<input id="cname" placeholder="เช่น Home strength 30 นาที"></label><label class="full-span">ท่าออกกำลังกาย<textarea id="citems" placeholder="Push-up | 3 | 10–15 | 60 sec\nSquat | 3 | 12 | 60 sec"></textarea></label></div><button class="primary full" onclick="saveCustom()">บันทึกโปรแกรม</button>`);window.saveCustom=()=>{let name=$('#cname').value.trim(), rows=$('#citems').value.trim().split('\n').filter(Boolean).map(r=>{let a=r.split('|').map(x=>x.trim());return {name:a[0],sets:Number(a[1])||3,reps:a[2]||'8–12',rest:a[3]||'60 sec'}});if(!name||!rows.length)return alert('กรอกชื่อและอย่างน้อย 1 ท่า');data.custom.push({name,items:rows});save();closeModal();go('plan')};
function modal(html,showClose=true){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-box">${showClose?'<button class="icon close" aria-label="ปิด" onclick="closeModal()">×</button>':''}${html}</div></div>`)} window.closeModal=()=>$('#modal')?.remove(); window.deleteLog=id=>{data.logs=data.logs.filter(x=>x.id!==id);save();render()}; window.exportData=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`hybrid-train-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};window.importData=f=>{if(!f)return;let r=new FileReader;r.onload=()=>{try{data=JSON.parse(r.result);save();render();toast('นำเข้าข้อมูลเรียบร้อย')}catch{toast('ไฟล์ไม่ถูกต้อง')}};r.readAsText(f)};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js'); render();
